{-# LANGUAGE ForeignFunctionInterface #-}

-- This file was generated by stechec2-generator. DO NOT EDIT.

module Champion where

import Api


-- Function called at the start of the game
init_game :: IO ()
init_game = return () -- TODO

-- Called when this is your turn to play
play_turn :: IO ()
play_turn = do
    gameBoard <- board
    let findMove [] = return ()
        findMove ((i, j):xs)
            | gameBoard !! (3 * j + i) == -1 = do
                _ <- play (Position i j)  -- On ignore le retour si ce n'est pas IO ()
                return ()
            | otherwise = findMove xs
    findMove [(i, j) | i <- [0..2], j <- [0..2]]

-- Function called at the end of the game
end_game :: IO ()
end_game = return ()


hs_init_game = init_game
foreign export ccall hs_init_game :: IO ()

hs_play_turn = play_turn
foreign export ccall hs_play_turn :: IO ()

hs_end_game = end_game
foreign export ccall hs_end_game :: IO ()
